### ISSUE TITLE
How do I sort by score? 

### ISSUE THREAD

**Issue by Goosegit11** [trickerer01/Ruxx#10]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

On rule34 you can place `sort:score` in tags and it will sort by score. 
Ruxx doesn't seem to work with `sort:score` tag. So how do I do that?

**Comment by trickerer01** [comment]
You can't override sorting unfortunatelly, only default sorting by ID enables date filter, so it's forced.
Use score tag instead: `score:>=500 score:<1000` and so on. Use check button to see the number of posts matching the tags before proceeding if you want. Note that RN uses score tag without colon `score>=500`.

![score](https://github.com/trickerer01/Ruxx/assets/76029665/72074ed0-2382-4191-afdb-a76879a5e83d)


Maybe I could add a check at launch so it's possible to use either date filter or sort tag but not both

**Comment by Goosegit11** [comment]
what are the "modules" - rn rs rx?

**Comment by trickerer01** [comment]
These are just abbreviations. Website names are only displayed at github home page.
- RN: rule34hentai.net
- RX: rule34.xxx
- RS: rule34.us

**Comment by Goosegit11** [comment]
Okay, thanks

> Maybe I could add a check at launch so it's possible to use either date filter or sort tag but not both
Yeah that would be okay, I'll be looking forward to this feature

**Comment by Goosegit11** [comment]
There's no new release so I need to compile it manually - but there's no build instructions in README.md
Please consider adding them

**Comment by Goosegit11** [comment]
Okay, `sort:score` works automatically. If you change the date then it wouldn't pass the check.
Looks good to me, thanks :+1:

**Comment by Goosegit11** [comment]
Wait, I checked and actually the files are not being downloaded in score order

**Comment by trickerer01** [comment]
> There's no new release so I need to compile it manually - but there's no build instructions in README.md Please consider adding them
> 
> upd: forgot that it's a Python project, sorry :-) so how does it work right now? is there any button/option or what?

I use my own build scripts but I'm not very experienced at python project distribution & maintainance so I don't share them. Also contain local paths and custom composed versioninfo for Windows, so - not very good.
But if you want to just build install PyInstaller package it use it on app_gui.py from root folder:
- `python -m PyInstaller src/app_gui.py -F --noupx -c -y -n Ruxx`

Note that it will be missing proper icon and revision in title

**Comment by trickerer01** [comment]
> Wait, I checked and actually the files are not being downloaded in score order

Tell me what kind of query you're trying to run so it is more clear what changes are requried to make it work

**Comment by Goosegit11** [comment]
`
Cmd: metal_gear_solid -gay -futanari -1animal -horse sort:score -module rx -path '/home/user/Downloads' -threads 8 -timeout 10 -retries 10 -prefix -dump_tags -dump_sources -dump_comments -append_info -warn_nonempty
`

**Comment by trickerer** [comment]
Do I understand correctly that idea here is to cancel downloading process at some point, when you decide you've downloaded enough? Is that the purpose of `sort:score` here?

**Comment by Goosegit11** [comment]
Yep

**Comment by trickerer01** [comment]
I always imagined such approach a problem since you risk getting unfinished files and Ruxx tries to delete those when download is cancelled.

Anyway, this change enables download order override using sort tag https://github.com/trickerer01/Ruxx/commit/6ceaa8d3eaad3311a1a3355ef4f936f40a2dd112

Also, if you really want the exact number of files downloaded there is actually a max downloads setting which is only exposed in debug mode or if ran using console. Set `__RUXX_DEBUG__` flag in app_revision.py to True to enable Debug features menu in GUI or use `-dlimit` flag in console.

**Comment by trickerer01** [comment]
https://github.com/trickerer01/Ruxx/releases/tag/2023.12.19
