### ISSUE TITLE
[Question] Module names

### ISSUE THREAD

**Issue by Ryuko-Ryukai** [trickerer01/Ruxx#11]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded question

what are differences between rs, rx and rn module ?

**Comment by trickerer** [comment]
They are different websites of course, abbreviations are used everywhere instead of website names. As for names themselves they are listed in repository description https://github.com/trickerer01/Ruxx. Also https://github.com/trickerer01/Ruxx/issues/10#issuecomment-1838467717
