### ISSUE TITLE
[Feature] make separate txts for each image.

### ISSUE THREAD

**Issue by PWDSerialgamer07** [trickerer01/Ruxx#12]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded description

It would be nice if you could have separate tag comment source txt for each image, so instead of it being like this:
```
image1.png
image2.png
tags.txt
sources.txt
comments.txt
```
It would be:
```
image1.png
tags1.png
sources1.png
comments1.png
image2.png
tags2.png
comments2.png
```

**Comment by trickerer01** [comment]
Sure I can add an option for that.

I wonder, what is your use case here?

**Comment by trickerer01** [comment]
https://github.com/trickerer01/Ruxx/commit/3d62f51283d576c1878a2f2e4eb64b8befd41ec6

Try it out

**Comment by PWDSerialgamer07** [comment]
Use case here is (badly) training a lora with scrapped content since I'm extremely lazy
