### ISSUE TITLE
How do I download all of my favorites from my account?

### ISSUE THREAD

**Issue by Brugbug7** [trickerer01/Ruxx#14]
- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded description

![Screenshot 2024-03-31 011353](https://github.com/trickerer01/Ruxx/assets/165541062/4a2ee004-4363-451d-a36a-6b5526ef8a3f)
I'm trying to download all of my favorites and I used the correct tags as you listed. What should have I typed instead?

### Provide verbose output that demonstrates the problem (use -verbose | Edit -> Verbose log)

```shell
Python 3.8.10
```

**Comment by trickerer01** [comment]
You're trying to use `favorited_by` meta tag with RX module. As you may have noticed from readme, `favorited_by` is a RN only tag.
- If you're trying to download your RN favorites then switch to RN module first
- If you're trying to download your RX favorites... well there is no similar tag for that which means downloading RX favorites is impossible using dapi. Long story short it isn't implemented yet.

**Comment by trickerer01** [comment]
https://github.com/trickerer01/Ruxx/releases/tag/2024.05.05
