### ISSUE TITLE
[Bug] download error

### ISSUE THREAD

**Issue by RomainLefranc** [trickerer01/Ruxx#17]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded description

![image](https://github.com/user-attachments/assets/e8587db7-7f8c-4ed4-8d40-7f0a9de05527)

I'm trying to download but there is an error in the log.

### Provide verbose output that demonstrates the problem (use -verbose | Edit -> Verbose log)

```shell
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Base args: C:\Users\lefra\Downloads\Programmes\Ruxx.exe
My args: Cmd: animated dzooworks -module rn -path 'F:/test/' -skip_img -threads 1 -headers {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"} -cookies {"cf_clearance": "x"} -timeout 10 -retries 10 -prefix -dump_tags -dump_sources -dump_comments -dump_per_item -append_info -warn_nonempty -verbose
```

**Comment by trickerer01** [comment]
Was fixed in r710: https://github.com/trickerer01/Ruxx/commit/dd9ef426c7b29001d66eb52aaa919333932f4fde
I see this isn't a pre-compiled version you're using so you should have no problems pulling the fix
