### ISSUE TITLE
Also allow ~ for rule34.xxx

### ISSUE THREAD

**Issue by JanDAXC** [Trickerer01/Ruxx#4]
On rule34.xxx you can add something like this: ( tag ~ othertag ) to the tags (= search for tag or othertag)
Ruxx gives me invalid tags again

**Comment by trickerer** [comment]
Read `Help->Tags` more carefully
> ~~( tag ~ othertag )~~
> (tag~othertag)

Note: this won't work with sort tags

**Comment by JanDAXC** [comment]
oh on the site it worked with spaces thanks
