### ISSUE TITLE
[Bug] ISSUE_TITLE

### ISSUE THREAD

**Issue by Ryukai-bg** [trickerer01/Ruxx#9]
### DO NOT REMOVE OR SKIP THE TEMPLATE

- [X] I understand that my issue may get **closed without notice** if I *intentionally* remove or skip any mandatory\* field

### Provide a well enough worded description

The date min/max function operate wrong

### Provide verbose output that demonstrated the problem (use -verbose | Edit -> Verbose log)

```shell
Cmd: clitoris -module rx -path 'C:/Users/Acer/Dropbox/PC/Downloads/clitoris_through_clothes/' -threads 8 -mindate 20-10-2023 -timeout 10 -prefix -dump_tags -dump_sources -dump_comments -append_info -warn_nonempty
```

**Comment by trickerer01** [comment]
My bad. Seems like I forgot to test latest changes to post date extraction.
Fixed in https://github.com/trickerer01/Ruxx/commit/6ab960bab0529df0995480599ac2a94954d90270.
I'll keep this issue open until next release.

**Comment by Ryukai-bg** [comment]
Okey dokey

Vào 20:04, T.3, 14 Th11, 2023 trickerer01 ***@***.***> đã
viết:

**Comment by trickerer01** [comment]
https://github.com/trickerer01/Ruxx/releases/tag/2023.11.20

**Comment by Ryukai-bg** [comment]
Thanks, I'll check it out!
